// FIXME this code was largely generated by AI to give an idea of structure. its needs rewriting.
#![allow(warnings)]

use crate::errors::AppError;
use reqwest::Client;
use serde::Serialize;

/// HTTP client for sending ActivityPub activities to remote servers
pub struct ActivityPubClient {
    http_client: Client,
    // TODO Add private key for signing requests
    // private_key: RsaPrivateKey,
    server_actor_id: String,
}

impl ActivityPubClient {
    pub fn new(server_actor_id: String) -> Self {
        Self {
            http_client: Client::new(),
            server_actor_id,
        }
    }

    /// POST an activity to a remote inbox URL
    /// Signs the request with HTTP Signatures for authentication
    pub async fn post_to_inbox<T: Serialize>(
        &self,
        inbox_url: &str,
        activity: &T,
    ) -> Result<(), AppError> {
        // TODO: Implement actual HTTP POST with signature
        // 1. Serialize activity to JSON
        // 2. Generate digest header (SHA-256 hash of body)
        // 3. Sign request with HTTP Signatures
        // 4. POST to inbox URL
        // 5. Handle response (200/202 = success, 4xx/5xx = error)

        tracing::info!("Would send activity to inbox: {}", inbox_url);

        // Placeholder implementation
        let _body = serde_json::to_string(activity)?;

        // TODO: Sign and send request
        // let response = self.http_client
        //     .post(inbox_url)
        //     .header("Content-Type", "application/activity+json")
        //     .header("Signature", signature)
        //     .body(body)
        //     .send()
        //     .await?;

        tracing::warn!("ActivityPub federation not yet implemented");
        Ok(())
    }

    /// Resolve an actor's inbox URL (for federation)
    /// This would typically fetch the actor document and extract the inbox property
    pub async fn resolve_inbox(&self, actor_id: &str) -> Result<String, AppError> {
        // TODO: Implement actor resolution
        // 1. Fetch actor document from actor_id URL
        // 2. Parse JSON
        // 3. Extract and return inbox URL

        tracing::info!("Would resolve inbox for actor: {}", actor_id);

        // Placeholder - just append /inbox for now
        Ok(format!("{}/inbox", actor_id))
    }
}
