// FIXME this code was largely generated by AI to give an idea of structure. its needs rewriting.
use crate::{errors::AppError, activitypub::Person};
use reqwest::Client;
use serde_json::Value;

/// Fetch a remote actor's Person document
pub async fn fetch_actor(actor_url: &str) -> Result<Person, AppError> {
    // TODO Implement actor fetching
    // 1. GET actor_url with Accept: application/activity+json
    // 2. Verify signature if present
    // 3. Parse and validate Person object
    // 4. Cache result (probably should do)
    
    tracing::info!("Fetch actor from: {}", actor_url);
    
    let client = Client::new();
    let response = client
        .get(actor_url)
        .header("Accept", "application/activity+json")
        .send()
        .await
        .map_err(|e| AppError::InternalError(anyhow::anyhow!("Failed to fetch actor: {}", e)))?;

    if !response.status().is_success() {
        return Err(AppError::NotFound(format!(
            "Actor not found: {}",
            actor_url
        )));
    }

    let person: Person = response
        .json()
        .await
        .map_err(|e| AppError::InternalError(anyhow::anyhow!("Failed to parse actor: {}", e)))?;

    Ok(person)
}

/// Fetch a remote object (generic ActivityPub object)
pub async fn fetch_object(object_url: &str) -> Result<Value, AppError> {
    // TODO Implement object fetching
    // Similar to fetch_actor but returns generic JSON
    
    tracing::info!("Fetch object from: {}", object_url);
    
    let client = Client::new();
    let response = client
        .get(object_url)
        .header("Accept", "application/activity+json")
        .send()
        .await
        .map_err(|e| AppError::InternalError(anyhow::anyhow!("Failed to fetch object: {}", e)))?;

    if !response.status().is_success() {
        return Err(AppError::NotFound(format!(
            "Object not found: {}",
            object_url
        )));
    }

    let object: Value = response
        .json()
        .await
        .map_err(|e| AppError::InternalError(anyhow::anyhow!("Failed to parse object: {}", e)))?;

    Ok(object)
}