// FIXME this code was largely generated by AI to give an idea of structure. its needs rewriting.
use crate::errors::AppError;
use serde_json::Value;

/// Validates the basic structure of an ActivityPub activity
pub fn validate_activity(activity: &Value) -> Result<(), AppError> {
    // TODO more activity validation like
    //    Validate actor URL format
    //    Validate activity type is supported
    //    Check object structure if present
    //    Validate Eko-specific requirements
    
    // Check for @context
    if !activity.get("@context").is_some() {
        // Not requiring it because ActivityPub says implementors "should" include it,
        // not "must" https://www.w3.org/TR/activitypub/#obj
        // TODO do we do something with @context?
        tracing::debug!("Activity missing @context")
    }
    
    // Check for required type
    if !activity.get("type").is_some() {
        return Err(AppError::BadRequest(
            "Activity missing type".to_string()
        ));
    }
    
    // Check for required actor
    if !activity.get("actor").is_some() {
        return Err(AppError::BadRequest(
            "Activity missing actor".to_string()
        ));
    }

    // Check for id
    if !activity.get("id").is_some() {
        // Not required because some objects are transient
        tracing::debug!("Activity is transient")
    }
    
    tracing::debug!("Activity validation passed (basic check only)");
    Ok(())
}

/// Validates that an activity type is supported by this server
pub fn is_supported_activity_type(activity_type: &str) -> bool {
    matches!(
        activity_type,
        "Create" | "Update" | "Delete" | "Follow" | "Accept" | "Reject" | "Add" | "Remove"
    )
}

/// Validates the structure of a Create activity specifically
pub fn validate_create_activity(activity: &Value) -> Result<(), AppError> {
    validate_activity(activity)?;
    
    // Check type is Create
    if activity.get("type").and_then(|t| t.as_str()) != Some("Create") {
        return Err(AppError::BadRequest(
            "Expected Create activity".to_string()
        ));
    }
    
    // Check for required object
    if !activity.get("object").is_some() {
        return Err(AppError::BadRequest(
            "Create activity missing object".to_string()
        ));
    }
    
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_validate_basic_activity() {
        let activity = json!({
            "@context": "https://www.w3.org/ns/activitystreams",
            "type": "Create",
            "actor": "https://example.com/users/alice"
        });
        
        assert!(validate_activity(&activity).is_ok());
    }

    #[test]
    fn test_validate_missing_context() {
        let activity = json!({
            "actor": "https://example.com/users/alice"
        });
        
        assert!(validate_activity(&activity).is_err());
    }

    #[test]
    fn test_supported_activity_types() {
        assert!(is_supported_activity_type("Create"));
        assert!(is_supported_activity_type("Update"));
        assert!(!is_supported_activity_type("Like"));
    }
}
